stages:
  split:
    cmd: python src/data/split_dataset.py
    deps:
    - data/raw_data
    - src/data/split_dataset.py
    outs:
    - data/processed_data
  scale:
    cmd: python src/data/scaled_dataset.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/scaled_dataset.py
    outs:
    - data/scaled_data
  gridsearch:
    cmd: python src/models/gridsearch_model.py
    deps:
    - data/scaled_data
    - src/models/gridsearch_model.py
    outs:
    - src/models/best_model.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/y_train.csv
    - data/scaled_data/X_train_scaled.csv
    - src/models/best_model.pkl
    - src/models/train_model.py
    outs:
    - src/models/trained_model.pkl
  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/y_test.csv
    - data/scaled_data/X_test_scaled.csv
    - src/models/trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - models/test_predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
